services:
  docuseal:
    image: docuseal/docuseal:latest
    container_name: docuseal
    ports:
      - "8200:3000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./data:/data
    environment:
#      - FORCE_SSL="true"
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/docuseal
  postgres:
    image: postgres:15
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: docuseal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
